### ISSUE TITLE
disable DEBUG flag in linker.urls ,alternative title : enable the default 404 page

### ISSUE THREAD

**Issue by Ayman0x03** [adamtherookie/linksharin#10]
**Describe the bug**

**To Reproduce**
1. you can visit any link that can produce a 404 page

**Expected behavior**
a clean 404 page
**Screenshots**
![image](https://user-images.githubusercontent.com/61380629/209153935-174b257e-e90a-4b1e-a5d3-7f8d77ef39c7.png)

**Desktop:**
 - OS: Arch linux 
 - Browser : chromium
 - Version : 97 (bundled in burpsuite)

**Comment by adamtherookie** [comment]
I disabled DEBUG on the server.
