### ISSUE TITLE
Make a cool 404 page

### ISSUE THREAD

**Issue by Ayman0x03** [adamtherookie/linksharin#11]
**Is your feature request related to a problem? Please describe.**
No 
**Describe the solution you'd like**
@adamtherookie spending an hour over-designing  a 404 page that anyone can say it takes 5min to make

**Comment by adamtherookie** [comment]
Don't worry, I will.

**Comment by adamtherookie** [comment]
Made a 404 page, closing.

**Comment by adamtherookie** [comment]
@all-contributors please add @Ayman0x03 for ideas and bug
