### ISSUE TITLE
Add more colorschemes, effects, and fonts

### ISSUE THREAD

**Issue by adamtherookie** [adamtherookie/linksharin#5]

**Comment by Rishav1707** [comment]
Elaborate your issues please??

**Comment by Rishav1707** [comment]
@adamtherookie Explain your issue please.

**Comment by adamtherookie** [comment]
> @adamtherookie Explain your issue please.

In the website/static/website/colorschemes and website/static/website/effects directories respectively there are self-explanatory CSS files for user page colorschemes and link hover effects. It's less of an issue and more of an enhancement because we currently only have 2 effects and about 7 colorschemes.

**Comment by Rishav1707** [comment]
OK

**Comment by adamtherookie** [comment]
Reopening, but won't accept any more colorscheme PRs until we have a decent amount of effects and fonts too.

**Comment by Rishav1707** [comment]
> Reopening, but won't accept any more colorscheme PRs until we have a decent amount of effects and fonts too.

ok

**Comment by adamtherookie** [comment]
@all-contributors please add @Rishav1707 for design and code.
